### ISSUE TITLE
HTML: Every paragraph should be prefixed with a full-width whitespace in Japanese

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#116]
<img width="1591" alt="Screenshot 2024-07-09 at 10 27 30 PM" src="https://github.com/metanorma/mn-samples-plateau/assets/11865/c34b0943-de24-4691-840c-6a633e5be82f">

**Comment by opoudjis** [comment]
Responding to https://github.com/metanorma/mn-samples-plateau/issues/119#issuecomment-2267240589

> i am wondering about the indents. i think we discussed that paragraph blocks have one double-byte-space as an indent, but i am concerned indents are possibly being added in more places (the title in the first row of the table actually looks indented on the left compared to the right margin). i will make some checks and open a separate issue if i find anything regarding that.

Like I said at the time, @ReesePlews, 

https://github.com/metanorma/mn-samples-plateau/issues/116#issuecomment-2230715188

> This is going to end in tears, as you are anticipating Reese, but ok, implementing...

I've implemented indentation before *any* paragraph. I fully expected that there are going to be cases where indentation is not applicable; and because I don't know about Japanese typography, I don't know what they are. That's up to the client or yourself to clarify.

@Intelligent2013 Once we have discrete rules, we will need to stop implementing indentation independently, and I will need to start doing indentation in Presentation XML. We also will need clarification about whether any indentation rules are applicable just to Plateau, or are generic to Japanese, and need to be implemented in JIS as well.

As you've stated, Reese, please open a new ticket once you have the requisite analysis.

**Comment by ReesePlews** [comment]
thank you @opoudjis i will open a new ticket once these things are clearly defined. i also find indents very confusing when i prepare documents in japanese.
