### ISSUE TITLE
Reference to list items within table not working?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#154]
Source:

```adoc
uro:matchingScoreは、以下に示す <<re_id_attrib_1>> から <<re_id_attrib_4>> の項
目のうち、「<<re_id_attrib_1>>、<<re_id_attrib_2>>及び<<re_id_attrib_4>>」又は
「<<re_id_attrib_1>>、<<re_id_attrib_3>>及び<<re_id_attrib_4>>」の3項目の各点数
の合計点（300点満点）の大きい方を100点満点に換算して算出する。

. [[re_id_attrib_1]]重なりスコア：建築物に紐づけられた登記簿の「所在」欄に記載されている土地と建築物を土地に投影した二次元空間属性の重なり割合（％）
+
式：重なり面積 ÷ 建築物の図形面積 × 100

. [[re_id_attrib_2]]階数スコア：建築物が地上階数をbldg:storeysBelowGround属性に保持している場合、建築物に紐づけられた登記簿の「床面積」欄から算出した地上階数と建築物の地上階数の一致度 地上階数が一致した場合は100点とする。一致しない場合は0点とする。

. [[re_id_attrib_3]]建築物高さスコア：建築物に紐づけられた登記簿の「床面積」欄から算出した地上階数から換算した高さと建築物の計測高さ(bldg:measuredHeight)の一致度
+
式：100－ABS（登記簿から算出した地上階数 × 2.95m + 1.95m ー 建築物の計測高さ) ABS（X）は、Xの絶対値とする。このときXは数値でなければならない。式の値が負の場合は0とする。

. [[re_id_attrib_4]]床面積スコア：建築物に紐づけられた登記簿の「床面積」欄から算出した各階ごとの床面積のうち最大となる床面積と建築物の図形面積の一致度 建築物がuro:buildingFootprintArea属性を保持している場合、登記簿から算出した面積と比較し、㎡単位で一致していた場合は100点とする。属性がない場合または㎡単位で一致していなければ以下を算出する。
+
式：100－ABS(登記データの1階床面積ー建築物の水平投影面積×0.8)登記データの1階床面積×100 ABS（X）は、Xの絶対値とする。このときXは数値でなければならない。式の値が負の場合は0とする。
```

Notice that the references are not rendered.

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/5878dc30-5c09-410e-951e-e06ebcaba29f">

**Comment by opoudjis** [comment]
This ticket has wasted 15 minutes of client time, because you (a) declined to provide complete markup, (b) declined to point to the context in a checked in document where this occurs, (c) this doesn't correspond to a checked in document to begin with, the checked in document still has it marked up as 「①、②及び④」又は「①、③及び④」, (d) I don't read Japanese, and (e) I certainly don't read flyspeck Japanese.

I have said  to you before that I am going to refuse to action tickets with insufficient information for me to replicate. That I have persevered to try to work out what is going on anyway is a tribute to my professionalism.

metanorma-iso is generating cross-references in this context, and so is metanorma-jis, so this is only metanorma-plateau. The bug was: to revert to ISO processing of list item cross-references from JIS behaviour, I was invoking an ISO Xref class; but the cross-reference objects it generated needed to be merged back into the Plateau cross-references.

Cross-references are now populating:

````
<td valign="top" align="left"><p id="_a5d9ce4c-3533-b876-aad1-42661efcea2b">uro:matchingScoreは、以下に示す <xref target="re_id_attrib_1">箇条 1 a)</xref> から <xref target="re_id_attrib_4">箇条 1 d)</xref> の項目のうち、「 <xref target="re_id_attrib_1">箇条 1 a)</xref>、<xref target="re_id_attrib_2">箇条 1 b)</xref>及び<xref target="re_id_attrib_4">箇条 1 d)</xref>」又は 「 <xref target="re_id_attrib_1">箇条 1 a)</xref>、<xref target="re_id_attrib_3">箇条 1 c)</xref>及び<xref target="re_id_attrib_4">箇条 1 d)</xref>」の3項目の各点数の合計点（300点満点）の大きい方を100点満点に換算して算出する。</p>
````
